motd=\u00a7bFancy Vanilla \u00a78| \u00a77vanilla z oprawa, progresja Tempered
max-players=15
view-distance=8
simulation-distance=6
difficulty=normal
gamemode=survival
pvp=true
spawn-protection=0
sync-chunk-writes=true
network-compression-threshold=256
enable-command-block=false
allow-flight=true
entity-broadcast-range-percentage=100
max-tick-time=60000
white-list=false
enforce-secure-profile=false
online-mode=true
level-name=world
